# webapp/app.yaml
application: restoassured
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: django
  version: latest

handlers:
 - url: /thebear*
   script: thebear.views

 - url: /core/*
   script: core.views
