# webapp/app.yaml
application: restoassured
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: django
  version: latest

handlers:
 - url: core/*
   script: core/urls.py

 - url: thebear/*
   script: thebear/urls.py
