#!/usr/bin/python
#Author: Emmanuel Odeke <odeke@ualberta.ca>

import re
import os
import stat
import time
outfile_perms = stat.S_IRWXU|stat.S_IRGRP|stat.S_IXGRP|stat.S_IXOTH|\
        stat.S_IROTH 
	
f = open("httpStatusCodes.txt")
httpDict = dict()
translatorName = re.findall("(\w+\.?\w+)$", __file__)

OUT_FILE = "httpStatusCodes.py"

outF = open(OUT_FILE, "w")
outF.write("#!/usr/bin/python\n")
outF.write("# This file was auto-generated by %s\n"%(translatorName[0]))
outF.write("# Time: %s\n"%(time.ctime()))
outF.write("\n# Codes \n")

for line in f:
  code_description = re.findall("([^:\s]+)\s+:\s+(.*)\n", line)
  if not code_description: continue
  code,desc = code_description[0]
  varName = re.findall("([^\(\)]+)\s{0,}\(?",desc)
  if not varName: continue
  
  capsVar = varName[0].upper()
  capsVar = re.sub("[\s-]","_", capsVar)
  capsVar = re.sub("[_]$","", capsVar)
  capsVar = re.sub("[']","",capsVar)
  print(code,capsVar)
  outF.write("%s = %s\n"%(capsVar,code))
  
os.chmod(OUT_FILE, outfile_perms)
outF.close()
f.close()
